const mongoose = require("mongoose");

const foodSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: String,
  price: { type: Number, required: true },
  originalPrice: { type: Number },
  discountPercentage: { type: Number, default: 0 },
  category: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
  restaurant: { type: mongoose.Schema.Types.ObjectId, ref: "Restaurant" },
  image: String,
  rating: { type: Number, default: 0 },
  reviews: [{ type: mongoose.Schema.Types.ObjectId, ref: "Review" }],
  isFeatured: { type: Boolean, default: false },
  isPopular: { type: Boolean, default: false },
  isBestSeller: { type: Boolean, default: false },
  isHealthy: { type: Boolean, default: false },
  isCombo: { type: Boolean, default: false },
  preparationTime: { type: Number, default: 20 }, // in minutes
  isVeg: { type: Boolean, default: true },
  isAvailable: { type: Boolean, default: true },
  popularityScore: { type: Number, default: 0 },
  tags: [{ type: String }],
  shortDescription: String,
  calories: { type: Number, default: 0 },
  protein: { type: Number, default: 0 },
  carbs: { type: Number, default: 0 },
  fat: { type: Number, default: 0 },
  servingSize: String,
  spiceLevel: { type: String, default: "Medium" },
  stock: { type: Number, default: 99 },
  isFreshArrival: { type: Boolean, default: false },
  isChefSpecial: { type: Boolean, default: false },
  isRecommended: { type: Boolean, default: false },
  isCustomizable: { type: Boolean, default: false },
  ingredients: [{ type: String }],
  allergens: [{ type: String }],
  sortOrder: { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("Food", foodSchema);
