const mockData = {
  categories: [
    { id: 1, name: "Pizza", icon: "pizza" },
    { id: 2, name: "Burger", icon: "hamburger" },
    { id: 3, name: "Biryani", icon: "rice" },
    { id: 4, name: "Chinese", icon: "noodles" },
    { id: 5, name: "South Indian", icon: "food-variant" },
    { id: 6, name: "Desserts", icon: "cupcake" },
    { id: 7, name: "Beverages", icon: "coffee" },
    { id: 8, name: "Breakfast", icon: "egg-fried" },
    { id: 9, name: "Snacks", icon: "food-variant" },
    { id: 10, name: "Combos", icon: "food-takeout-box" },
  ],
  restaurants: [
    {
      id: 1,
      name: "Krushna's Restaurant",
      image:
        "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=800&q=80",
      rating: 4.4,
      deliveryTime: "30-40 mins",
      cuisine: ["Pizza", "Burger", "South Indian", "Breakfast"],
    },
  ],
  foods: [
    // ─── Morning Items ───────────────────────────────────
    {
      id: 101,
      name: "Masala Dosa",
      description: "Crispy golden dosa stuffed with spiced potato filling, served with sambar and chutney.",
      price: 89,
      rating: 4.8,
      deliveryTime: "20 mins",
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "South Indian",
      restaurantId: 1,
      mealTime: ["morning"],
      isBestseller: true,
      isVeg: true,
    },
    {
      id: 102,
      name: "Poha",
      description: "Fluffy flattened rice tempered with mustard seeds, curry leaves, peanuts and lemon.",
      price: 55,
      rating: 4.5,
      deliveryTime: "15 mins",
      image: "https://images.unsplash.com/photo-1626132647523-66c3c5ef7ef5?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Breakfast",
      restaurantId: 1,
      mealTime: ["morning"],
      isVeg: true,
    },
    {
      id: 103,
      name: "Upma",
      description: "Savory semolina porridge cooked with vegetables and tempered with spices.",
      price: 60,
      rating: 4.3,
      deliveryTime: "15 mins",
      image: "https://images.unsplash.com/photo-1567337710282-00832b415979?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Breakfast",
      restaurantId: 1,
      mealTime: ["morning"],
      isVeg: true,
    },
    {
      id: 104,
      name: "Masala Chai",
      description: "Aromatic Indian spiced tea brewed with ginger, cardamom, cinnamon and fresh milk.",
      price: 30,
      rating: 4.7,
      deliveryTime: "10 mins",
      image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Beverages",
      restaurantId: 1,
      mealTime: ["morning", "evening"],
      isVeg: true,
    },
    {
      id: 105,
      name: "Bread Omelette",
      description: "Fluffy egg omelette stuffed between buttered toast slices with veggies.",
      price: 70,
      rating: 4.4,
      deliveryTime: "12 mins",
      image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Breakfast",
      restaurantId: 1,
      mealTime: ["morning"],
      isVeg: false,
    },
    {
      id: 106,
      name: "Idli Sambar",
      description: "Soft steamed rice cakes served with piping hot lentil soup and chutneys.",
      price: 70,
      rating: 4.6,
      deliveryTime: "18 mins",
      image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "South Indian",
      restaurantId: 1,
      mealTime: ["morning"],
      isBestseller: true,
      isVeg: true,
    },
    {
      id: 107,
      name: "Aloo Paratha",
      description: "Whole wheat flatbread stuffed with spiced mashed potatoes, served with butter and pickle.",
      price: 80,
      rating: 4.5,
      deliveryTime: "20 mins",
      image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Breakfast",
      restaurantId: 1,
      mealTime: ["morning"],
      isVeg: true,
    },

    // ─── Afternoon Items ──────────────────────────────────
    {
      id: 201,
      name: "Chicken Biryani",
      description: "Rich basmati rice layered with spiced chicken, caramelized onions and saffron.",
      price: 220,
      rating: 4.9,
      deliveryTime: "35 mins",
      image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Biryani",
      restaurantId: 1,
      mealTime: ["afternoon", "night"],
      isBestseller: true,
      isVeg: false,
    },
    {
      id: 202,
      name: "Dal Tadka",
      description: "Yellow lentils simmered slow and finished with a smoky ghee tempering.",
      price: 110,
      rating: 4.6,
      deliveryTime: "25 mins",
      image: "https://images.unsplash.com/photo-1546833998-877b37c2e5c6?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "South Indian",
      restaurantId: 1,
      mealTime: ["afternoon"],
      isVeg: true,
    },
    {
      id: 203,
      name: "Paneer Butter Masala",
      description: "Creamy tomato-based curry with soft paneer cubes and buttery finish.",
      price: 160,
      rating: 4.7,
      deliveryTime: "28 mins",
      image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "South Indian",
      restaurantId: 1,
      mealTime: ["afternoon"],
      isBestseller: true,
      isVeg: true,
    },
    {
      id: 204,
      name: "Veg Thali",
      description: "Complete Indian meal with dal, sabzi, roti, rice, salad and dessert.",
      price: 180,
      rating: 4.5,
      deliveryTime: "30 mins",
      image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "South Indian",
      restaurantId: 1,
      mealTime: ["afternoon"],
      isVeg: true,
    },
    {
      id: 205,
      name: "Veg Fried Rice",
      description: "Wok-tossed basmati rice with colorful vegetables, soy sauce and sesame oil.",
      price: 130,
      rating: 4.4,
      deliveryTime: "22 mins",
      image: "https://images.unsplash.com/photo-1603133872871-7a2acf087d74?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Chinese",
      restaurantId: 1,
      mealTime: ["afternoon", "evening"],
      isVeg: true,
    },
    {
      id: 206,
      name: "Butter Roti",
      description: "Soft whole wheat flatbread fresh off the tawa, brushed with home-made butter.",
      price: 20,
      rating: 4.3,
      deliveryTime: "10 mins",
      image: "https://images.unsplash.com/photo-1619894991209-9f9694be045a?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Breakfast",
      restaurantId: 1,
      mealTime: ["afternoon"],
      isVeg: true,
    },

    // ─── Evening Items ────────────────────────────────────
    {
      id: 301,
      name: "Chicken Burger",
      description: "Juicy grilled chicken patty with fresh lettuce, tomato and signature sauce.",
      price: 149,
      rating: 4.6,
      deliveryTime: "25 mins",
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Burger",
      restaurantId: 1,
      mealTime: ["evening", "night"],
      isBestseller: true,
      isVeg: false,
    },
    {
      id: 302,
      name: "Margherita Pizza",
      description: "Classic thin-crust pizza with rich tomato sauce, fresh mozzarella and basil.",
      price: 249,
      rating: 4.7,
      deliveryTime: "30 mins",
      image: "https://images.unsplash.com/photo-1594007653308-d4d8d2ab5d73?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Pizza",
      restaurantId: 1,
      mealTime: ["evening", "night"],
      isBestseller: true,
      isVeg: true,
    },
    {
      id: 303,
      name: "Veg Momos",
      description: "Soft steamed dumplings filled with spiced cabbage, carrot and paneer.",
      price: 99,
      rating: 4.5,
      deliveryTime: "20 mins",
      image: "https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Snacks",
      restaurantId: 1,
      mealTime: ["evening"],
      isVeg: true,
    },
    {
      id: 304,
      name: "Masala Fries",
      description: "Crispy golden fries tossed in house masala spice blend.",
      price: 79,
      rating: 4.4,
      deliveryTime: "15 mins",
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Snacks",
      restaurantId: 1,
      mealTime: ["evening"],
      isVeg: true,
    },
    {
      id: 305,
      name: "Cold Coffee",
      description: "Rich chilled coffee blended with milk and ice cream, topped with whipped cream.",
      price: 99,
      rating: 4.6,
      deliveryTime: "12 mins",
      image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Beverages",
      restaurantId: 1,
      mealTime: ["evening"],
      isVeg: true,
    },
    {
      id: 306,
      name: "Paneer Wrap",
      description: "Grilled paneer tikka, crispy onions and mint chutney rolled in a soft tortilla.",
      price: 129,
      rating: 4.5,
      deliveryTime: "18 mins",
      image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Snacks",
      restaurantId: 1,
      mealTime: ["evening"],
      isBestseller: true,
      isVeg: true,
    },

    // ─── Night Items ──────────────────────────────────────
    {
      id: 401,
      name: "Veg Biryani",
      description: "Aromatic basmati rice layered with seasonal vegetables and whole spices.",
      price: 160,
      rating: 4.6,
      deliveryTime: "30 mins",
      image: "https://images.unsplash.com/photo-1645177628172-a8b7c3e7fae4?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Biryani",
      restaurantId: 1,
      mealTime: ["afternoon", "night"],
      isVeg: true,
    },
    {
      id: 402,
      name: "Maggi Masala",
      description: "Classic 2-minute noodles cooked with vegetables and extra masala.",
      price: 60,
      rating: 4.3,
      deliveryTime: "12 mins",
      image: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Snacks",
      restaurantId: 1,
      mealTime: ["night"],
      isVeg: true,
    },
    {
      id: 403,
      name: "Chicken Shawarma",
      description: "Middle-Eastern style grilled chicken with garlic sauce and pickled vegetables.",
      price: 149,
      rating: 4.7,
      deliveryTime: "22 mins",
      image: "https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Snacks",
      restaurantId: 1,
      mealTime: ["evening", "night"],
      isBestseller: true,
      isVeg: false,
    },
    {
      id: 404,
      name: "Ice Cream Sundae",
      description: "Three scoops of vanilla ice cream drizzled with hot chocolate fudge and nuts.",
      price: 119,
      rating: 4.8,
      deliveryTime: "15 mins",
      image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Desserts",
      restaurantId: 1,
      mealTime: ["evening", "night"],
      isVeg: true,
    },
    {
      id: 405,
      name: "Veg Manchurian",
      description: "Crispy veg balls tossed in a tangy Indo-Chinese soy-garlic sauce.",
      price: 120,
      rating: 4.4,
      deliveryTime: "25 mins",
      image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      category: "Chinese",
      restaurantId: 1,
      mealTime: ["afternoon", "evening", "night"],
      isVeg: true,
    },
  ],
  featured: [
    {
      id: 501,
      name: "Weekend Feast Combo",
      description: "Special combo with pizza, burger, and fries.",
      image:
        "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
      price: 499,
      rating: 4.7,
    },
  ],
  popular: [
    {
      id: 301,
      name: "Chicken Burger",
      price: 149,
      rating: 4.6,
      deliveryTime: "25 mins",
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
    },
    {
      id: 302,
      name: "Margherita Pizza",
      price: 249,
      rating: 4.7,
      deliveryTime: "30 mins",
      image: "https://images.unsplash.com/photo-1594007653308-d4d8d2ab5d73?auto=format&fit=crop&w=800&q=80",
      restaurant: "Krushna's Restaurant",
    },
  ],
  orders: [
    {
      id: 301,
      orderNumber: "FE1001",
      status: "Preparing",
      totalAmount: 498,
      items: [
        { food: { name: "Margherita Pizza" }, quantity: 1 },
        { food: { name: "Cold Coffee" }, quantity: 2 },
      ],
    },
    {
      id: 302,
      orderNumber: "FE1002",
      status: "Delivered",
      totalAmount: 369,
      items: [{ food: { name: "Chicken Burger" }, quantity: 1 }],
    },
  ],
  wishlist: [
    {
      id: 301,
      name: "Chicken Burger",
      restaurant: "Krushna's Restaurant",
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
      price: 149,
    },
  ],
  notifications: [
    {
      id: 401,
      title: "50% off on your next order",
      description: "Use code FOODIE50 at checkout.",
      type: "Offer",
    },
    {
      id: 402,
      title: "Order FE1001 is on the way",
      description: "Your Margherita Pizza is out for delivery.",
      type: "Order",
    },
  ],
};

export default mockData;
